### ISSUE TITLE
Access to the Dockerfile

### ISSUE THREAD

**Issue by szigetics** [OlivierLDff/QQuickStaticHelloWorld#1]
Hi! Could you please grant access to the Dockerfile (preferrably on Docker Hub)?

**Comment by OlivierLDff** [comment]
I'm not sure what you are asking for?
https://github.com/OlivierLDff?tab=repositories&q=docker&type=&language=&sort=
All the Dockerfile I used are on github

**Comment by szigetics** [comment]
> I'm not sure what you are asking for?
> https://github.com/OlivierLDff?tab=repositories&q=docker&type=&language=&sort=
> All the Dockerfile I used are on github

Exactly for this : https://github.com/OlivierLDff/QtWasmCMakeDocker/blob/main/Dockerfile .

Thank you! 👍
